-- Get procedure signature (parameters)
SELECT 
    RDB$PROCEDURE_NAME as PROCEDURE_NAME,
    RDB$PARAMETER_NAME as PARAMETER_NAME,
    RDB$PARAMETER_NUMBER as PARAM_ORDER,
    RDB$PARAMETER_TYPE as PARAM_TYPE
FROM RDB$PROCEDURE_PARAMETERS
WHERE RDB$PROCEDURE_NAME = 'P_UPDATEITEMS'
ORDER BY RDB$PARAMETER_NUMBER;

-- Search for procedures that call P_UPDATEITEMS
SELECT 
    'CALLER' as TYPE,
    TRIM(RDB$PROCEDURE_NAME) as PROCEDURE_NAME
FROM RDB$PROCEDURES
WHERE 
    UPPER(RDB$PROCEDURE_SOURCE) CONTAINING 'P_UPDATEITEMS'
    AND RDB$PROCEDURE_NAME <> 'P_UPDATEITEMS'
    AND RDB$SYSTEM_FLAG = 0;

-- Search for triggers that call P_UPDATEITEMS  
SELECT 
    'TRIGGER' as TYPE,
    TRIM(RDB$TRIGGER_NAME) as NAME,
    TRIM(RDB$RELATION_NAME) as TABLE_NAME
FROM RDB$TRIGGERS
WHERE 
    UPPER(RDB$TRIGGER_SOURCE) CONTAINING 'P_UPDATEITEMS'
    AND RDB$SYSTEM_FLAG = 0;
