-- Find how P_UPDATEITEMS is called
SELECT 
    TRIM(RDB$PROCEDURE_NAME) as CALLER,
    SUBSTRING(RDB$PROCEDURE_SOURCE FROM 1 FOR 5000) as SOURCE_SNIPPET
FROM RDB$PROCEDURES
WHERE 
    UPPER(RDB$PROCEDURE_SOURCE) CONTAINING 'P_UPDATEITEMS'
    AND RDB$PROCEDURE_NAME <> 'P_UPDATEITEMS';
