SET LIST ON;

-- Get P_UPDATEITEMS source
SELECT 
    TRIM(RDB$PROCEDURE_NAME) as PROCEDURE_NAME,
    RDB$PROCEDURE_SOURCE as SOURCE
FROM RDB$PROCEDURES
WHERE RDB$PROCEDURE_NAME = 'P_UPDATEITEMS';

-- Get calling procedures source
SELECT 
    TRIM(RDB$PROCEDURE_NAME) as PROCEDURE_NAME,
    RDB$PROCEDURE_SOURCE as SOURCE
FROM RDB$PROCEDURES
WHERE 
    RDB$PROCEDURE_NAME IN ('P_UPDATEDEPARTMENTVARIANT', 'P_CREATEUPDATEITEMS');
