SET HEADING ON;
SET LIST ON;

-- Get the VAREFRVSTR triggers that reference BC_UPDATEDATE
SELECT 
    TRIM(RDB$TRIGGER_NAME) as TRIGGER_NAME,
    RDB$TRIGGER_TYPE as TRIGGER_TYPE,
    RDB$TRIGGER_SOURCE as SOURCE
FROM RDB$TRIGGERS
WHERE 
    RDB$TRIGGER_NAME IN ('INS_VAREFRVSTR', 'VAREFRVSTR_BC_CHANGES')
    AND RDB$SYSTEM_FLAG = 0;

-- Get the stored procedure
SELECT 
    TRIM(RDB$PROCEDURE_NAME) as PROCEDURE_NAME,
    RDB$PROCEDURE_SOURCE as SOURCE
FROM RDB$PROCEDURES
WHERE 
    RDB$PROCEDURE_NAME = 'P_UPDATEITEMS';

-- Check if there's an index on BC_UPDATEDATE
SELECT 
    TRIM(I.RDB$INDEX_NAME) as INDEX_NAME,
    I.RDB$UNIQUE_FLAG as IS_UNIQUE,
    I.RDB$INDEX_TYPE as INDEX_TYPE
FROM RDB$INDICES I
WHERE 
    I.RDB$INDEX_NAME = 'VARER_BC_UPDATEDATE';
