-- Search for BC_UPDATEDATE in all database objects

SET HEADING ON;
SET LIST ON;

-- 1. Check ALL triggers (not just VARER) that might reference BC_UPDATEDATE
SELECT 
    'TRIGGER' as OBJECT_TYPE,
    TRIM(RDB$TRIGGER_NAME) as OBJECT_NAME,
    TRIM(RDB$RELATION_NAME) as TABLE_NAME,
    RDB$TRIGGER_TYPE as TRIGGER_TYPE
FROM RDB$TRIGGERS
WHERE 
    UPPER(RDB$TRIGGER_SOURCE) CONTAINING 'BC_UPDATEDATE'
    AND RDB$SYSTEM_FLAG = 0;

-- 2. Check stored procedures that might reference BC_UPDATEDATE
SELECT 
    'PROCEDURE' as OBJECT_TYPE,
    TRIM(RDB$PROCEDURE_NAME) as OBJECT_NAME
FROM RDB$PROCEDURES
WHERE 
    UPPER(RDB$PROCEDURE_SOURCE) CONTAINING 'BC_UPDATEDATE'
    AND RDB$SYSTEM_FLAG = 0;

-- 3. Check views that might reference BC_UPDATEDATE
SELECT 
    'VIEW' as OBJECT_TYPE,
    TRIM(RDB$RELATION_NAME) as OBJECT_NAME
FROM RDB$RELATIONS
WHERE 
    RDB$VIEW_SOURCE CONTAINING 'BC_UPDATEDATE'
    AND RDB$SYSTEM_FLAG = 0;

-- 4. Check if BC_UPDATEDATE exists in other tables
SELECT 
    'FIELD' as OBJECT_TYPE,
    TRIM(RDB$RELATION_NAME) as TABLE_NAME,
    TRIM(RDB$FIELD_NAME) as FIELD_NAME
FROM RDB$RELATION_FIELDS
WHERE 
    UPPER(TRIM(RDB$FIELD_NAME)) = 'BC_UPDATEDATE';

-- 5. Check for any computed fields based on BC_UPDATEDATE
SELECT 
    'COMPUTED_FIELD' as OBJECT_TYPE,
    TRIM(RDB$RELATION_NAME) as TABLE_NAME,
    TRIM(RDB$FIELD_NAME) as FIELD_NAME,
    RDB$COMPUTED_SOURCE as COMPUTATION
FROM RDB$RELATION_FIELDS
WHERE 
    UPPER(RDB$COMPUTED_SOURCE) CONTAINING 'BC_UPDATEDATE';

-- 6. Check indices that use BC_UPDATEDATE
SELECT 
    'INDEX' as OBJECT_TYPE,
    TRIM(I.RDB$INDEX_NAME) as INDEX_NAME,
    TRIM(I.RDB$RELATION_NAME) as TABLE_NAME,
    TRIM(S.RDB$FIELD_NAME) as FIELD_NAME
FROM RDB$INDICES I
JOIN RDB$INDEX_SEGMENTS S ON I.RDB$INDEX_NAME = S.RDB$INDEX_NAME
WHERE 
    UPPER(TRIM(S.RDB$FIELD_NAME)) = 'BC_UPDATEDATE';
